async page => {
  const checks=[], errors=[];
  page.on('pageerror', e=>errors.push(e.message));
  const check = (ok,label)=>checks.push({label,pass:!!ok});
  const button = name=>page.getByRole('button',{name,exact:true});
  const field = name=>page.getByRole('spinbutton',{name,exact:true});
  const edit = async(name,value,blur=true)=>{await field(name).fill(String(value));if(blur)await field(name).press('Tab');};
  const data = ()=>page.evaluate(()=>JSON.parse(localStorage.getItem('houseplanner.project.v1')));
  await page.goto('http://127.0.0.1:8765/');
  await page.evaluate(()=>localStorage.removeItem('houseplanner.project.v1')); await page.reload();
  await button('Bookshelf builder').click();
  await page.getByRole('textbox',{name:'Design name',exact:true}).fill('No blur saved');
  await page.reload(); await button('Bookshelf builder').click();
  check(await page.getByRole('textbox',{name:'Design name',exact:true}).inputValue()==='No blur saved','typing survives reload without blur or waiting for autosave');
  await page.getByRole('combobox',{name:'Room',exact:true}).selectOption({label:'Office'});
  for(const preset of ['Framed','Staggered','Stepped edges']) {
    await button(preset).click(); await edit('Width, cm',180);
    check(!await button('Save design').isDisabled(),preset+' shrinks to 180 cm without detached boards');
    await edit('Width, cm',300);check(!await button('Save design').isDisabled(),preset+' expands to 300 cm');
    await edit('Width, cm',240);
  }
  await edit('Width, cm',180,false); await field('Width, cm').press('Tab');
  check(await page.evaluate(()=>document.activeElement?.dataset.bs==='height'),'Tab after width moves to height');
  await edit('Height, cm',190,false); await field('Height, cm').press('Tab');
  check(await page.evaluate(()=>document.activeElement?.dataset.bs==='depth'),'Tab after height moves to depth');
  await edit('Depth, cm',35);
  await page.getByRole('button',{name:/^S2 /}).click();
  await edit('Underside, cm',42,false);await field('Underside, cm').press('Tab');
  check(await page.evaluate(()=>document.activeElement?.dataset.bs==='left'),'Tab inside shelf editor keeps the next field focused');
  await button('Undo').click();
  await page.getByRole('button',{name:/^S1 /}).click();
  check(await field('Underside, cm').isDisabled(),'bottom height cannot accidentally break geometry');
  const baseDividers=await page.locator('#bsRowEditor .bs-divider').count();
  await button('+ Divider').click();await button('+ Divider').click();
  check(await page.locator('#bsRowEditor .bs-divider').count()===baseDividers+2 && !await button('Save design').isDisabled(),'repeated divider additions choose free spaces');
  await page.getByRole('button',{name:/^Remove divider D1\./}).last().click();
  check(await page.locator('#bsRowEditor .bs-divider').count()===baseDividers+1,'remove divider works');
  await button('Undo').click();await button('Undo').click();await button('Undo').click();
  const count=await page.locator('#bsLevels button').count();
  await button('+ Shelf').click();check(await page.locator('#bsLevels button').count()===count+1,'add shelf splits a bay');
  await button('Remove this shelf').click();check(await page.locator('#bsLevels button').count()===count,'remove added shelf restores count');
  const d=page.locator('#bsDrawing [data-bs-board="D1.2"] rect');await d.scrollIntoViewIfNeeded();const rect=await d.boundingBox();
  const old=await field('D1.2 centre from left, cm').inputValue();
  await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await page.mouse.down();await page.mouse.move(rect.x+12,rect.y+rect.height/2,{steps:6});await page.mouse.up();
  check(await field('D1.2 centre from left, cm').inputValue()!==old,'multi-step divider drag updates exact position');await button('Undo').click();
  await edit('Left edge, cm',100,false);check(await button('Save design').isDisabled(),'detached supports block saving and exports');
  check(await button('Download cut list').isDisabled(),'invalid geometry cannot export a cut list');await button('Undo').click();
  await edit('Width, cm','',false);check(await button('Save design').isDisabled(),'empty dimensions block save while typing');
  await field('Width, cm').press('Tab');check(await field('Width, cm').inputValue()==='180','invalid field keeps last valid value on leaving it');
  await page.getByRole('combobox',{name:'Wall',exact:true}).selectOption('s');check(await button('Save & place on wall').isDisabled(),'windows and radiators block wall placement');
  await page.getByRole('combobox',{name:'Wall',exact:true}).selectOption('n');await edit('Wall offset, cm',340);
  check((await page.locator('#bsProblems').innerText()).includes('door'),'door conflict explained');
  await page.getByRole('combobox',{name:'Wall',exact:true}).selectOption('e');await edit('Wall offset, cm',30);await edit('Wall gap, cm',3);
  await page.getByRole('textbox',{name:'Design name',exact:true}).fill('Saved east-wall design');await button('Save design').click();
  let s=await data(), p=s.catalog.find(p=>p.name==='Saved east-wall design');
  check(p?.shelfTarget?.wall==='e'&&p.shelfTarget.offset===30&&p.shelfTarget.gap===3,'saved catalog design stores the chosen wall and offset');
  check(!s.rooms.flatMap(r=>r.items).some(i=>i.catalogId===p.id),'save-only does not place furniture');
  await button('New design').click();await page.getByRole('combobox',{name:'Saved bookshelf designs',exact:true}).selectOption(p.id);
  check(await page.getByRole('combobox',{name:'Wall',exact:true}).inputValue()==='e'&&await field('Wall offset, cm').inputValue()==='30','reopening a saved design remembers wall');
  await button('Save & place on wall').click();await page.reload();await button('Bookshelf builder').click();
  s=await data();check(s.rooms.flatMap(r=>r.items).filter(i=>i.catalogId===p.id).length===1,'save-and-place survives immediate reload with one placement');
  await page.getByRole('combobox',{name:'Saved bookshelf designs',exact:true}).selectOption(p.id);
  check(await button('Save & move placement').isVisible(),'reopening placed design selects its existing placement');
  await button('Save & move placement').click();s=await data();check(s.rooms.flatMap(r=>r.items).filter(i=>i.catalogId===p.id).length===1,'re-save-and-place does not duplicate placement');
  await page.getByRole('combobox',{name:'Room',exact:true}).selectOption({label:'Living room'});
  await page.getByRole('combobox',{name:'Wall',exact:true}).selectOption('n');await edit('Wall offset, cm',20);
  await button('Save & move placement').click();s=await data();
  check(s.rooms.find(r=>r.seedId==='living').items.some(i=>i.catalogId===p.id)&&!s.rooms.find(r=>r.seedId==='office').items.some(i=>i.catalogId===p.id),'move relocates the original item between rooms');
  await button('Make a copy').click();await edit('Depth, cm',40);await button('Save design').click();s=await data();
  check(s.catalog.filter(p=>p.shelfDesign).length===2&&s.catalog.find(x=>x.id===p.id).d===35,'copy saves independent geometry');
  const downloads=[];
  for(const [name,ext] of [['Download cut list','csv'],['Download build plan','html'],['Export design JSON','json']]){
    const event=page.waitForEvent('download');await button(name).click();const result=await event;await result.saveAs('output/playwright/acceptance.'+ext);downloads.push(result.suggestedFilename());
  }
  check(downloads.length===3,'all three workshop downloads complete');
  const popupEvent=page.waitForEvent('popup');await button('Print / save PDF').click();const popup=await popupEvent;
  await popup.waitForLoadState();check(await popup.locator('tbody tr').count()===26,'print plan contains every board');await popup.close();
  await page.setViewportSize({width:390,height:844});check(await page.evaluate(()=>document.documentElement.scrollWidth<=390),'phone width has no horizontal overflow');
  await page.screenshot({path:'output/playwright/acceptance-phone.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'output/playwright/acceptance-desktop.png',fullPage:true});
  check(await page.locator('#bs3d canvas').count()===1,'orbitable 3D preview is present');
  const geometry=await page.evaluate(()=>{
    const d=JSON.parse(localStorage.getItem('houseplanner.project.v1')).bookshelfDraft.design,parts=Bookshelf.boards(d);
    const g=HouseModels.buildItem({type:'shelf',w:d.width,d:d.depth,h:d.height,color:'#A46B42',shelfDesign:d,elev:1},{evening:false});g.updateMatrixWorld(true);
    return parts.every((b,i)=>{const size=new THREE.Box3().setFromObject(g.children[i]).getSize(new THREE.Vector3());return Math.abs(size.x-b.w)<1e-4&&Math.abs(size.y-b.h)<1e-4&&Math.abs(size.z-d.depth)<1e-4;});
  });check(geometry,'every measured 3D board matches cut dimensions');
  await button('Back to room').click();
  await page.locator('#plan [data-item]').filter({has:page.locator('title',{hasText:'Saved east-wall design'})}).first().click();
  check(await button('Edit bookshelf').isVisible(),'placed bookshelf has a clear way back to the builder');
  await button('Edit bookshelf').click();
  await button('Save and versions').click();
  await page.getByRole('textbox',{name:'Version name',exact:true}).fill('Bookshelf acceptance snapshot');await button('Save version').click();
  await button('Close').click();
  const backupEvent=page.waitForEvent('download');await button('Save and versions').click();await button('Export backup').click();const backup=await backupEvent;
  await backup.saveAs('output/playwright/acceptance-backup.json');await button('Close').click();
  check(!errors.length,'no JavaScript errors during the complete flow');
  const failures=checks.filter(c=>!c.pass);
  if(failures.length||errors.length)throw new Error(JSON.stringify({failures,errors}));
  return {checks:checks.length,failures,errors};
}
